### PR TITLE
Add :fail-fast? option

### LINKED ISSUE #1: Option to stop on first failure
It would be quite nice to be able to run "until first failure", perhaps as a mode. Even better would be to start the next test run with said failure.

### PR DESCRIPTION
**Pull request by Deraen**
Closes #1 

Not sure if approach with each fixtures here is correct, but this seems to work. If I added the test to existing `test-var` fn, the fixtures were run for all test vars after failure. Now that I moved `each-fixtures` call to inside the check, no more fixtures are run after a failure.

I tested this with following fixture:

```clj
(def c (atom 0))

(use-fixtures :each (fn [f]
                      (println "each" (swap! c inc))
                      (f)))
```

### CODE REVIEW

**Comment by weavejester** [comment]
Could you squash your commits? I was going to manually merge the PR into master, but I see you've merged master into the PR.

**Comment by Deraen** [comment]
@weavejester Squashed both PRs.

**Comment by Deraen** [comment]
Btw. noticed a test is failing, but this happens even without my PRs, could be the catch output feature?

**Comment by weavejester** [comment]
Maybe. I'll take a look. The tests passed last I checked... I should really add them to the CI.

**Pull request merged**
