### PR TITLE
Add time notation to testcase in jUnit output

### PR DESCRIPTION
**Pull request by jcf**
Hi, @weavejester,

I notice #79 has been in limbo for a little while, and wondered if I could help move things along by completing the small change you requested on top of @yanatan16's work.

All the best!

### CODE REVIEW

**Comment by mpenet** [comment]
👍 I have been using this patch and it seems to just work. It would be great is it was evaluated/merged

**Comment by weavejester** [comment]
Looks like the notification for this slipped by me. This looks fine, I'll merge it in.

**Comment by mpenet** [comment]
nice! Could you please do a release with this change?

**Comment by weavejester** [comment]
Done!

**Pull request merged**
